### ISSUE TITLE
Improve fuzzy description of RHEL product lifecycle

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/grommunio-documentation#14]
As of writing, [kb/update_cycle.rst](https://github.com/grommunio/grommunio-documentation/blob/707eef0e6a4b6d1d94374dcc6ea581924640ba20/kb/update_cycle.rst) is IMHO written in a fuzzy way related to RHEL and its derivates. It gives the impression that there would be a (major) RHEL release every 6-8 months, which actually isn't the case.

On 2019-05-07, Red Hat Enterprise Linux 8 (8.0) was released. On 2019-11-05, Red Hat Enterprise Linux 8.1 was released. It is important to understand that 8.1 is not a new major release, just a larger patch update "bundle", that maybe could be called "service pack". A RHEL user does not have to switch from RHEL 8.0 to 8.1 by subscribing another update channel (which I personally know from ancient SLES releases), a regular `dnf update` will provide just "more updates", which are still fully backwards compatible (which at least in ancient times was different for SLES SPs, thinking of e.g. forced PHP 5.1→5.2 rebases or so). If you run `dnf update` e.g. on a monthly base, you maybe even won't directly notice that you switched from RHEL 8.0 to 8.1; some would call this maybe even "rolling release".

As an example: RHEL 8.0 shipped PHP 7.4 – and it will continue to ship PHP 7.4 (of course with patches for security and bug fixes) until the end-of-life of RHEL 8 in 2029. RHEL 8 will not rebase to a newer version (and yes, AppStreams, the new feature of RHEL 8, provide _optionally_ newer PHP versions with a shorter lifecycle). But as a user, there is no obligation to ever update to something newer than PHP 7.4 for the whole RHEL 8 lifecycle.

One of the main purposes of having a RHEL 8.1 is a new installation media so that e.g. new kernel driver support can be reflected there. This is especially important for new hardware released after the RHEL 8.0 release (e.g. RAID controllers, network interface cards or other basic chipsets, where installation media support is essential to get things flying at all). And of course using a RHEL 8.1 installation media for a fresh system avoids to take a RHEL 8.0 installation media and downloading various updates. Comparing with a version control system, I would call RHEL 8.1 more a "tag" that marks a specific point of the overall RHEL 8 product lifecycle with a name.

Aside of this: There still is CentOS, but it needs to be distinguished between CentOS Linux <= 8 and CentOS Stream >= 8. CentOS Linux was/is a RHEL clone/rebuild/derivative (_was_ because of CentOS Linux 8, which is EOL; however there still _is_ CentOS Linux 7). Given Red Hat terminated CentOS Linux, others, such as AlmaLinux or Rocky Linux, came up to fill this gap. CentOS Stream however is the upstream of RHEL and has a "branch" per release. CentOS Stream 8 contains what ends later in RHEL 8. And CentOS Stream 9 contains what ends later in RHEL 9.

While the regular [RHEL lifecycle](https://access.redhat.com/support/policy/updates/errata) of a major RHEL release, such as e.g. RHEL 8, is 10 years, it can be even extended using a paid add-on subscription to 12-13 years (the exact maximum add-on length of the so-called "Extended Lifecycle Support" (ELS) is defined by Red Hat per RHEL major release and announced early). RHEL clones/rebuilds/derivatives usually do not pick up ELS but retire the product after 10 years (like CentOS Linux <= 7 did in the past).

Given the full backwards compatibility of RHEL minor releases, I can not see how the "update cadence" would be in favor of SLES. When looking to the [SUSE Linux Enterprise Server 15 SP4 Upgrade Guide](https://documentation.suse.com/sles/15-SP4/single-html/SLES-upgrade/index.html), I even get the impression that it could be the other way: It is not supported to e.g. directly update to SLES 15 SP4 when still staying on SLES 15 GA without LTSS and without ESPOS. Not sure why I can't skip multiple SLES SPs, but RHEL does not care if you are still on RHEL 8.0 (because you didn't update for the last 3 years at all), because a `dnf update` will directly lead to RHEL 8.7 (without any intermediate updates). Oh, and the same applies for RHEL clones/rebuild/derivatives, too.

From my point of view the current description and comparison should be updated and improved to reflect the correct actual situation for both enterprise distributions clearly and comprehensive. I am very happy to provide a pull request (if you let me know which direction is desired for this document) and/or to review (and maybe enhance) other suggestions to achieve this.

**Comment by jengelh** [comment]
The description was changed to put more emphasis on service packs.

**Comment by jengelh** [comment]
If you feel this needs more change, make a PR like you always do.
(But brevity is key for this particular file.)
