### ISSUE TITLE
Missing documentation of secure default permissions for /etc/gromox/mysql_adaptor.cfg

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/grommunio-documentation#23]
As of writing, [`admin/manual_core.rst`](https://github.com/grommunio/grommunio-documentation/blob/master/admin/manual_core.rst) does currently not mention the correct file permissions for `/etc/gromox/mysql_adaptor.cfg`, which leads due to `umask` defaults and/or when following the steps closely, to a world-readable configuration file (`root:root` and `0644`), which might be treated as security flaw, e.g. [CWE-276: Incorrect Default Permissions](https://cwe.mitre.org/data/definitions/276.html). While I would expect a system running grommunio to be sealed system (= not to be used by regular shell users), this can not be expected in general, nor does it seem to be required by the documentation.

Based on some tests, the following file permissions seem to work for all tested grommunio (core) components:

```
-rw-r-----. 1 grommunio gromoxcf 123 May  7 22:22 /etc/gromox/mysql_adaptor.cfg
```

But `grommunio:gromoxcf` can't be considered really good configuration style, because it makes the `/etc/gromox/mysql_adaptor.cfg` file writable to every process running as user `grommunio` (and thus such permissions are discouraged at Fedora and RHEL). Better permissions would be `root:<some-group>` and `0640`, so that the configuration file can only be read-only accessed by `<some-group>` (practically I wasn't able to find a single grommunio system group suitable to get all grommunio components up and running afterwards).

**Comment by jengelh** [comment]
37be9f38aedd96e1d89ce0a1e35af24fbb320da9

>writable to every process running as user `grommunio` (and thus such permissions are discouraged at Fedora and RHEL)

Only grommunio-admin-api.service uses that identity, and there, it is by design. The alternative would be to run grommunio-admin-api.service as root (like cupsd), which sucks too and then a bit.
You can keep file ownership at root:gromoxcf if you don't plan on using AAPI to change configuration.

(This was already reviewed by SUSE earlier, and gromox is in the distribution since.)
