### ISSUE TITLE
Insecure default permissions for /etc/gromox/mysql_adaptor.cfg in openSUSE-based appliance

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/grommunio-documentation#24]
Closely related to #23: As of writing, the latest openSUSE-based grommunio appliance creates a `/etc/gromox/mysql_adaptor.cfg` configuration file that looks regarding the file permissions like this:

```
# ls -ld /etc/gromox/
drwxr-xr-x 2 grommunio gromoxcf 290 May  7 22:02 /etc/gromox/
# 
```

```
# ls -l /etc/gromox/mysql_adaptor.cfg 
-rw-r--r-- 1 root root 122 May  7 22:02 /etc/gromox/mysql_adaptor.cfg
# 
```

This means `/etc/gromox/mysql_adaptor.cfg` is by default word-readable; this might be treated as security flaw, e.g. [CWE-276: Incorrect Default Permissions](https://cwe.mitre.org/data/definitions/276.html). While I would expect the openSUSE-based grommunio appliance to be sealed system (= not to be used by regular shell users), this can not be expected in general, nor does it seem to be required by the documentation.

**Comment by robert-scheck** [comment]
After reporting https://github.com/grommunio/gromox/issues/96, I would like to add that the default permissions of `/etc/gromox/` are incorrect as well (`0755` instead of `0750`).

**Comment by jengelh** [comment]
https://github.com/grommunio/grommunio-index/commit/175d11d892b0691497ebc493eb20ed9096b6e709
https://github.com/grommunio/grommunio-setup/commit/b985a596f37928fc572651a6ccdadf770c699b4b
